/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk_test;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ReAlfz
 */
public class D_siswa extends javax.swing.JFrame {

    /**
     * Creates new form D_siswa
     */
    public D_siswa() {
        initComponents();
        loads();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tables = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_buat = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_nisn = new javax.swing.JTextField();
        txt_nis = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_idKelas = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_telp = new javax.swing.JTextField();
        txt_idSpp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nisn", "Nis", "Nama", "Id Kelas", "Alamat", "No Telp", "Id Spp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tables);

        jLabel1.setText("Nisn");

        jLabel2.setText("Nis");

        jLabel3.setText("Nama");

        jLabel4.setText("Id Kelas");

        jLabel5.setText("Alamat");

        jLabel6.setText("No Telp");

        jLabel7.setText("Id Spp");

        btn_buat.setText("Buat");
        btn_buat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buatActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txt_idKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idKelasActionPerformed(evt);
            }
        });

        txt_idSpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idSppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(74, 74, 74))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(47, 47, 47)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_nis, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_nisn, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_idKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_alamat)
                                    .addComponent(txt_telp)
                                    .addComponent(txt_idSpp, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                                .addGap(173, 173, 173)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_buat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(132, 132, 132)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nisn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buat))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btn_ubah))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btn_hapus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idSpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton4))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idKelasActionPerformed

    private void txt_idSppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idSppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idSppActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Admin().show();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try{
            String sql, id;
            
            id = txt_nisn.getText();
            sql = "DELETE FROM siswa WHERE nisn = '"+id+"' ";
            Connection conn = (Connection)Config.config();
            java.sql.PreparedStatement pst = conn.prepareCall(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
                    
            loads();
            hapused();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesMouseClicked
        String nisn, nis, nama, idKelas, alamat, telp, idSpp;
        int list = tables.rowAtPoint(evt.getPoint());
        
        nisn = tables.getValueAt(list, 0).toString();
        txt_nisn.setText(nisn);
        
        nis = tables.getValueAt(list, 1).toString();
        txt_nis.setText(nis);
        
        nama = tables.getValueAt(list, 2).toString();
        txt_nama.setText(nama);
        
        idKelas = tables.getValueAt(list, 3).toString();
        txt_idKelas.setText(idKelas);
        
        alamat = tables.getValueAt(list, 4).toString();
        txt_alamat.setText(alamat);
        
        telp = tables.getValueAt(list, 5).toString();;
        txt_telp.setText(telp);
        
        idSpp = tables.getValueAt(list, 6).toString();
        txt_idSpp.setText(idSpp);
    }//GEN-LAST:event_tablesMouseClicked

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        String nisn, nis, nama, idKelas, alamat, telp, idSpp;
        
        nisn = txt_nisn.getText();
        nis = txt_nis.getText();
        nama = txt_nama.getText();
        idKelas = txt_idKelas.getText();
        alamat = txt_alamat.getText();
        telp = txt_telp.getText();
        idSpp = txt_idSpp.getText();
        
        try{
            String sql = "UPDATE siswa SET nis = '"+nis+"', nama = '"+nama+"', id_kelas = '"+idKelas+"', alamat = '"+alamat+"', no_telp = '"+telp+"', id_spp = '"+idSpp+"' WHERE nisn = '"+nisn+"' ";
            Connection conn = (Connection)Config.config();
            java.sql.PreparedStatement pst = conn.prepareCall(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil di ubah");
            
            loads();
            hapused();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_buatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buatActionPerformed
        String sql ,nisn, nis, nama, idKelas, alamat, telp, idSpp;
        
        nisn = txt_nisn.getText();
        nis = txt_nis.getText();
        nama = txt_nama.getText();
        idKelas = txt_idKelas.getText();
        alamat = txt_alamat.getText();
        telp = txt_telp.getText();
        idSpp = txt_idSpp.getText();
        
        if (nisn.equals("") || nisn.length() == 0){
            JOptionPane.showMessageDialog(this, "Masukan nisn");
        } else if (nisn.length() > 11 ){
            JOptionPane.showMessageDialog(this, "Maksimal karakter nisn adalah 11");
        } else if (nis.equals("") ||  nis.length() == 0){
            JOptionPane.showMessageDialog(this, "Masukan nis");
        } else if (nis.length() > 8){
            JOptionPane.showMessageDialog(this, "Maksimal karakter nis adalah 8");
        } else if (nama.equals("")){
            JOptionPane.showMessageDialog(this, "Masukan nama");
        } else if (idKelas.equals("") ||  idKelas.length() == 0){
            JOptionPane.showMessageDialog(this, "Masukan id Kelas");
        } else if (idKelas.length() > 11){
            JOptionPane.showMessageDialog(this, "Maksimal karakter id kelas adalah 11");
        } else if (alamat.equals("")){
            JOptionPane.showMessageDialog(this, "Masukan alamat");
        } else if (telp.equals("") ||  telp.length() == 0){
            JOptionPane.showMessageDialog(this, "Masukan no telpon");
        } else if (telp.length() > 13){
            JOptionPane.showMessageDialog(this, "Maksimal karakter no telpon adalah 13");
        } else if (idSpp.equals("") ||  idSpp.length() == 0){
            JOptionPane.showMessageDialog(this, "Masukan id Spp");
        } else if (idSpp.length() > 11){
            JOptionPane.showMessageDialog(this, "Maksimal karakter id spp adalah 11");
        }
        
        try{ 
            sql = "INSERT into 'siswa' ('nisn', 'nis', 'nama', 'id_kelas', 'alamat', 'no_telp', 'id_spp') values ('"+nisn+"', '"+nis+"', '"+nama+"', '"+idKelas+"', '"+alamat+"', '"+telp+"', '"+idSpp+"') ";
            Connection conn = (Connection)Config.config();
            java.sql.PreparedStatement pst = conn.prepareCall(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil ditambahkan");
            
            loads();
            hapused();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_buatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new D_siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buat;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tables;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_idKelas;
    private javax.swing.JTextField txt_idSpp;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nis;
    private javax.swing.JTextField txt_nisn;
    private javax.swing.JTextField txt_telp;
    // End of variables declaration//GEN-END:variables

    private void loads() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nisn");
        model.addColumn("Nis");
        model.addColumn("Nama");
        model.addColumn("Id Kelas");
        model.addColumn("Alamat");
        model.addColumn("No Telp");
        model.addColumn("Id Spp");
        
        try{
          String sql = "SELECT * FROM siswa";
          java.sql.Connection conn = (Connection)Config.config();
          java.sql.Statement stm = conn.createStatement();
          java.sql.ResultSet res = stm.executeQuery(sql);
          while(res.next()){
              model.addRow(new Object[]{
                  res.getString(1),
                  res.getString(2),
                  res.getString(3),
                  res.getString(4),
                  res.getString(5),
                  res.getString(6),
                  res.getString(7)
              });
              tables.setModel(model);
          }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void hapused() {
        txt_nisn.setText("");
        txt_alamat.setText("");
        txt_idKelas.setText("");
        txt_idSpp.setText("");
        txt_nama.setText("");
        txt_nis.setText("");
        txt_telp.setText("");
    }
}
